config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("myapp/", include("myapp.urls")),
    path("video/", include("video.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from . import views


app_name = "myapp"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

video/urls.py
from django.urls import path
from . import views


app_name = "video"

urlpatterns = [
    path("", views.index, name="index"),
    path("upload/", views.upload, name="upload"),
    path("<int:video_id>/detail/", views.detail, name="detail")
]

myapp/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib import admin

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    @admin.display(
            boolean=True,
            ordering = "pub_date",
            description="Published recently?"
    )
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    

video/models.py
from django.db import models
from django.utils import timezone

class VideoContent(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    upload_date = models.DateTimeField(auto_now_add=True)
    files = models.FileField(upload_to="files")
    thumbnail_image = models.FileField(upload_to="thumbnail", default="")

    

video/forms.py
from django import forms
from .models import VideoContent

class VideoCreateForm(forms.ModelForm):
    class Meta:
        model = VideoContent
        fields = "__all__"

myapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.

# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     context = {
#         "latest_question_list": latest_question_list,
#     }
#     return render(request, "myapp/index.html", context)

class IndexView(generic.ListView):
    template_name = "myapp/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]

# ver.1
# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exit")
#     return render(request, "myapp/detail.html", {"question": question})

# ver.2
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "myapp/detail.html", {"question": question})

class DetailView(generic.DetailView):
    model = Question
    template_name = "myapp/detail.html"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "myapp/results.html", {"question": question})

class ResultsView(generic.DetailView):
    model = Question
    template_name = "myapp/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "myapp/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("myapp:results", args=(question.id,)))

video/views.py
from django.shortcuts import render, redirect
from .models import VideoContent
from .forms import VideoCreateForm

def index(request):
    videos = VideoContent.objects.all()
    context = {
        "videos": videos,
    }

    return render(request, "video/index.html", context)

def upload(request):
    if request.method == "POST":
        form = VideoCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("video:index")
    else:
        form = VideoCreateForm()
    
    context = {
        "form": form
    }
    return render(request, "video/form.html", context)
    
def detail(request, video_id):
    video = VideoContent.objects.get(pk=video_id)

    context = {
        "video": video
    }

    return render(request, "video/detail.html", context)

templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>MyApp</title>
  </head>
  <body>
    <nav class="nav">
      <a class="nav-link active" href="{% url 'video:index' %}">HOME</a>
      <a class="nav-link" href="{%url 'video:upload'%}">UPLOAD</a>
      <a class="nav-link" href="/admin">ADMIN</a>
    </nav>
    


    {% block main %}


    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/myapp/detail.html
<form action="{% url 'myapp:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

templates/myapp/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'myapp/style.css' %}">
{% if latest_question_list %}

	<ul>
		{% for question in latest_question_list %}
		<li><a href="{% url 'myapp:detail' question.id %}">{{question.question_text}}</a></li>
		{% endfor %}
	</ul>

{% else %}
	<p>No polls are available</p>
{% endif %}

templates/myapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>

<a href="{% url 'myapp:detail' question.id %}">Vote again?</a>

templates/video/detail.html
{% extends "base.html" %}

{% block main %}

{% load static %}

<link rel="stylesheet" href="{% static 'video/style.css' %}">


<div class="block-center">
    <div>
        <video src="{{video.files.url}}" poster="{{video.thumbnail_image.url}}" controls></video>
    </div>
    <h1>{{video.title}}</h1>
    <h3>{{video.upload_date}}</h3>
    <p>{{video.description}}</p>
    <a href="{% url 'video:index' %}">一覧に戻る</a>
</div>

{% endblock %}

templates/video/form.html
{% extends "base.html" %}

{% block main %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">送信</button>
</form>

{% endblock %}

templates/video/index.html
{% extends "base.html" %}

{% block main %}


{% load static %}

<link rel="stylesheet" href="{% static 'video/style.css' %}">


<h1>video index</h1>
<div class="contents">
{% for video in videos %}
    <div class="video-content-box">
        <a href="{% url 'video:detail' video.id %}">
            <div>
                <div class="thumbnail_image">
                    <img src="{{video.thumbnail_image.url}}">
                </div>
                <div class="text-box">
                    <h2>{{video.title}}</h2>
                    <p>{{video.description}}</p>
                </div>
            </div>
        </a>
    </div>
{% endfor %}
</div>


{% endblock %}